name: Upgrade
main: com.tropicalwikis.tuxcraft.plugins.upgrade.UpgradePlugin
version: 0.1.1
author: [tuxed,XeonPowder(Lars1011)]
commands:
    rankup:
        description: Rank yourself up
permissions:
    upgrade.*:
        description: Alias for rankup and reload permissions
        children:
            upgrade.rankup: true
            upgrade.reload: true
    upgrade.rankup:
        description: Let users rank up
    upgrade.reload:
        description: Reload the plugin
        default: op
